name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: {}

jobs:
  ci:
    name: CI
    permissions:
      contents: read
    uses: FollowTheProcess/ci/.github/workflows/Go.yml@v3
    with:
      # Skip integration tests and code coverage (as it should include those)
      # these are run below in their own step
      test-flags: -short
      codecov: false

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Setup Testcontainers
        uses: docker/setup-docker-action@v4
        with:
          rootless: true

      - name: Run Tests
        env:
          # -race needs CGO (https://go.dev/doc/articles/race_detector#Requirements)
          CGO_ENABLED: 1
        run: go test -race -cover -covermode=atomic -coverprofile=./coverage.out ./...

      - name: Coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out

  bats:
    name: Bats Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Setup Bats
        id: bats
        uses: bats-core/bats-action@3.0.1
        with:
          support-path: "${{ github.workspace }}/tests/bats-support"
          assert-path: "${{ github.workspace }}/tests/bats-assert"
          detik-path: "${{ github.workspace }}/tests/bats-detik"
          file-path: "${{ github.workspace }}/tests/bats-file"

      - name: Build Test Binary
        run: mkdir -p ./bin && go build -o ./bin/zap -ldflags='-s -w -X go.followtheprocess.codes/zap/internal/cmd.version=test' ./cmd/zap

      - name: Bats Tests
        env:
          BATS_LIB_PATH: ${{ steps.bats.outputs.lib-path }}
          TERM: xterm
        run: bats tests
